### ISSUE TITLE
A `RuntimeError` is being thrown when instantiating a `BRabbit` object.

### ISSUE THREAD

**Issue by wiseaidev** [nidhaloff/b-rabbit#18]
* b_rabbit version: `1.2.4`
* Python version: `3.9.10`
* Operating System: Ubuntu `20.04`

### Description

I am trying to contribute unit tests for this project. However, I am getting a `RuntimeError` whenever I create an instance of class `BRabbit`.

### What I Did

```python
from b_rabbit import BRabbit
rabbit = BRabbit(host='localhost', port=5672)
```

### Output

```sh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/harmouch/b-rabbit/b_rabbit/b_rabbit.py", line 59, in __init__
    self.connection = rabbitpy.Connection(
  File "/home/harmouch/b-rabbit/.venv/lib/python3.9/site-packages/rabbitpy-2.0.1-py3.9.egg/rabbitpy/connection.py", line 131, in __init__
    self._connect()
  File "/home/harmouch/b-rabbit/.venv/lib/python3.9/site-packages/rabbitpy-2.0.1-py3.9.egg/rabbitpy/connection.py", line 301, in _connect
    raise RuntimeError("Timeout waiting for opening the socket")
RuntimeError: Timeout waiting for opening the socket
```

**Comment by nidhaloff** [comment]
@wiseaidev this has nothing to do with BRabbit. I think you need to check if rabbitmq is running and configured on your host
